spring.application.name=eventmanager

# swagger
springdoc.swagger-ui.url=/event-manager-openapi.yaml

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=root

# Jpa
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Security
jwt.secret=yq2B7mK9pX3vR8tL5nQ1zA6cF4jH2wE0uY9iO3sD5gN8kP7mT
jwt.secret.lifetime=7200000