spring.application.name=event-notificator
server.port=8081

# Datasource
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/kafka}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}

# Jpa
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Security
jwt.secret=${JWT_SECRET:yq2B7mK9pX3vR8tL5nQ1zA6cF4jH2wE0uY9iO3sD5gN8kP7mT}
jwt.secret.lifetime=${JWT_LIFETIME:7200000}