spring.application.name=event-notificator
server.port=8081

# Datasource
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/kafka}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}

# Jpa
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Security
jwt.secret=${JWT_SECRET:yq2B7mK9pX3vR8tL5nQ1zA6cF4jH2wE0uY9iO3sD5gN8kP7mT}
jwt.secret.lifetime=${JWT_LIFETIME:7200000}

# Kafka (consumer)
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP:localhost:9092}
spring.kafka.consumer.group-id=event-notificator
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.LongDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.course.eventcommon.kafka
spring.kafka.consumer.properties.spring.json.value.default.type=com.course.eventcommon.kafka.EventMessage
app.kafka.topic.domain-events=${KAFKA_TOPIC:event-domain-events}
notification_cleanup_cron=${NOTIFICATION_CLEANUP_CRON:0 0 3 * * *}

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=2000ms